/* 
**  mod_http_fingerprint_mod.c -- Apache sample http_fingerprint_mod module
**  [Autogenerated via ``apxs -n http_fingerprint_mod -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_http_fingerprint_mod.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /http_fingerprint_mod in as follows:
**
**    #   apache2.conf
**    LoadModule http_fingerprint_mod_module modules/mod_http_fingerprint_mod.so
**    <Location /http_fingerprint_mod>
**    SetHandler http_fingerprint_mod
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /http_fingerprint_mod and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/http_fingerprint_mod 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_http_fingerprint_mod.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

/* The sample content handler */
static int http_fingerprint_mod_handler(request_rec *r)
{
    if (strcmp(r->handler, "http_fingerprint_mod")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_http_fingerprint_mod.c\n", r);
    return OK;
}

static void http_fingerprint_mod_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(http_fingerprint_mod_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA http_fingerprint_mod_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    http_fingerprint_mod_register_hooks  /* register hooks                      */
};

